### ISSUE TITLE
Java Code Conventions

### ISSUE THREAD

**Issue by finagin** [viacheslav-s/Geek#1]
https://github.com/viacheslav-s/Geek/blob/044d3ce9deae2a470ed69a962b99171106e2ee02/lesson_5/src/com/Geekbrains/employee.java#L3

> Class names should be nouns, in mixed case with the first letter of each internal word capitalized. Try to keep your class names simple and descriptive. Use whole words-avoid acronyms and abbreviations (unless the abbreviation is much more widely used than the long form, such as URL or HTML). > [proof](http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-135099.html#367)

**Comment by viacheslav-s** [comment]
lol, пасиб :)
мне уже об этом сказали, и что методы нужно называть с маленькой буквы, а классы с большой

**Comment by finagin** [comment]
А ты чё это в Java ударился?))

**Comment by viacheslav-s** [comment]
очень давно хотел, и вот наконец решился)
это курсы в GeekBrains

**Comment by finagin** [comment]
![NullPointerException](http://fignya.ucoz.com/file.gif)
